- name: first playbook
  hosts: localhost
  become: yes
  tasks: 
  - name: First task
    ansible.builtin.debug:
      msg: "Hi this is my Frist message from TASK-1"

- name: second playbook
  hosts: localhost
  become: yes
  tasks: 
  - name: first task from second playbook
    ansible.builtin.debug:
    msg: "Hi I am from second palybook"