- name: Regarding Variables
  hosts: localhost
  vars: #variable Declaration
    Bowler: "Styne" # Good practice is mention variables in Caps
    Batter: "Miller"
    Fielder: "Kaif"
  tasks:
  - name: printing variables
    ansble.builtin.debug:
      msg: "The final over of the {{Bowler}}, the {{Batter}} caught by {{Fielder}} at 99 runs"
      #In this ansible variable calls in this braces {{variable}}
