- name: checking variables in task level and vars level
  hosts: localhost
  become: yes
  vars:
    Bowler: "Styne"
    Batter: "Miller"
    Fielder: "Kaif"
  tasks:
  - name: checking variables in task level
    vars: # if you are mention vars in task level, it is nth but overriding of variables
      Bowler: "Ameer Md"
      Batter: "Kane"
      Fielder: "Collingwood"
    ansible.builtin.debug: # This is debug for printing messages # msg:
      msg: "The final over of the {{Bowler}}, the {{Batter}} caught by {{Fielder}} at 99 runs"
  
  - name: checking 
    ansible.builtin.debug:
      msg: "The final over of the {{Bowler}}, the {{Batter}} caught by {{Fielder}} at 99 runs"