- name: Checking inventory variables
  hosts: localhost
  become: yes
  vars:
  
  tasks: 
  - name: printing inventory variables
    ansible.builtin.debug:
      msg: "The final over of the {{Bowler}} the {{Batter}} caught by {{Fielder}} at 99 runs"
    