- name: Just say Ansible Ping Pong play book
  hosts: localhost
  #become: yes
  tasks:
  - name: ping
    ansible.builtin.ping:

- name: ping the server
  hosts: web
  tasks: #list of tasks/modules/collections
  - name: pinging the server
    ansible.builtin.ping:
   