- name: playbook for Nginx
  hosts: localhost
  become: yes
  tasks:
  - name: Installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: present
    
  -name: enabling nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes